### ISSUE TITLE
MECHANIC: Does immolation aura fall off you once you leave Metamorphosis?

### ISSUE THREAD

**Issue by Virtuosowow** [Zephancode/wotlk-warlock#16]
Immolation Aura is a spell which can only be used while you're in Metamorphosis, but Immolation Aura is a self buff which lasts for 15s (depends on haste). So the question is, does immolation aura cancel itself once Metamorphosis falls off? Another question relating to this is that can using Glyph of Metamorphosis allow you to use two FULL immolation auras in one Metamorphosis?

**Comment by Shukrat** [comment]
It falls off when you leave Metamorphosis.

You cannot do two full immolation auras in one Metamorphosis due to this.  Cooldown on Immolation aura is 30 seconds.
