### ISSUE TITLE
[TEST-REQUEST] 4T5 corruption damage

### ISSUE THREAD

**Issue by Putridbeast** [Zephancode/wotlk-warlock#27]
## 1. Describe the mechanic
In original wrath beta the multiplicative stacking damage bonus on corruption from 4T5 worked with everlasting affliction to hit damage cap. check to see this bug is not present.

### 1.1 To Test
Steps to test the behavior:
1. Talent into Everlasting Affliction
2. Equipe 4 pieces of T5
3. Go over to a training dummy cast corruption, and keep it up by refreshing with Everlasting Affliction
4. Does Corruption Damage keep increasing infinitely?

**Comment by NoCement** [comment]
4p t5 set bonus was changed on Wrath, so test = find t5 priece in bank and check if it is changed on Wrath.

**Comment by Zephancode** [comment]
In that case you don't even need to log in as wowhead pulls data from the WoTLK beta.

https://www.wowhead.com/wotlk/item-set=646/corrupt or-raiment seems the change is in.
