### ISSUE TITLE
[TEST-REQUEST] The lightning capacitator giving charge on dot crit?

### ISSUE THREAD

**Issue by Deliw** [Zephancode/wotlk-warlock#34]
## 1. Describe the mechanic
While dot can't crit in TBC, it can in WOTLK.
Is dot crit giving a charge for The Lightning Capacitator trinket?

### 1.1 To Test
Steps to test the behavior:
1. Dot a mob
2. Wait for crit
3. Check stacks
4. Check proc

**Comment by nodddle** [comment]
I don't have a TLC on a lock, so I did it on my ele shaman. flameshock dot did not give charges of TLC when it crit.

**Comment by Pummelx** [comment]
Went cookie cutter affliction and tested all dots while watching for crits. Only proc I received was when Haunt crit on the initial use. Does not seem as if dot crits are generating TLC procs.

**Comment by Deliw** [comment]
2 members confirmed that it didn't work
