### ISSUE TITLE
[TEST-REQUEST] Naxx enchants (heirloom purposes)

### ISSUE THREAD

**Issue by Oiledsenior** [Zephancode/wotlk-warlock#35]
Currently, Naxx enchants are tradeable via. BOE items allowing you to enchant a BOE item & then trade it.
In the past, Naxx enchants were tradeable (briefly) via the trade window.
In WOTLK, there are minimum character levels attached to most shoulder enchants, but I'm unaware of conclusive proof for this on naxx enchants due to their limited availability previously.

### 1.1 To Test
Steps to test the behavior:
1. a) Find a player with a naxx enchant
2. a) Attempt to trade the naxx enchant via the trade window onto both a soulbound, and a non-soulbound item (white and green suggested)

1. b) Find your own naxx enchant
2. b) Enchant your own white & green item, trading it to another player & attempting to mail it to an alt.

3. Check for level requirements added to the shoulder enchant. If possible to trade, trade to a low-level and re-check level requirements.

**Comment by Tharre** [comment]
Seer's Mantle and Double-stiched Woolen Shoulders with the Power of the Scourge Naxx enchant.

1a) & 2a) "You can only use this on an object you own"
3b)/4b) They become soulbound; can't trade or mail them to anyone.
5) Level requirements don't change, at least in the UI (can't trade them to a low-level character obviously)

**Comment by Oiledsenior** [comment]
Thanks for testing, that's a huge weight off regarding heirlooms. Might leave the door open for pre-existing twink shoulder enchants as per 5) but oh well.
