### ISSUE TITLE
[TEST-REQUEST] - Does Metamorphosis DMG increase stack with ToT damage increase?

### ISSUE THREAD

**Issue by NoCement** [Zephancode/wotlk-warlock#42]
## 1. Describe the mechanic
Does Metamorphosis DMG increase stack with ToT damage increase?

### 1.1 To Test
Steps to test the behavior:
1. Spec Demonology to Metamorphosis
2. Cast a spell with constant DMG (Corruption for example)
3. Take screenshot of DMG with visible buffs
4. Request some rogue to use Tricks of the Trade on you, then Metamorphosis
5. Cast the same spell under same conditions (SP, Gear, debuffs) except having ToT on top of that
6. Collect evidence as before - ideally post a screenshot here
7. Try to switch ToT and Meta order - first Meta, then ToT. Shouldn't matter but better be sure

**Comment by nodddle** [comment]
looks like they do stack, here's my testing:

https://youtu.be/RHUnf5uZlpM

**Comment by NoCement** [comment]
Confirmed, it stacks.
