### ISSUE TITLE
[TEST-REQUEST]  The Egg of Mortal Essence, How does it interact with Corruption's healing

### ISSUE THREAD

**Issue by bradleyman88** [Zephancode/wotlk-warlock#43]
## 1. The Egg of Mortal Essence
The Egg has a haste proc chance on direct heal and heal over time spells. 
Corruption, while being a damage over time spell, has it's own mechanic, if talented, that heals every tick of damage it does.
Does this "Heal over time" part of corruption proc the Egg's haste proc?

### 1.1 To Test
Steps to test the behavior:
1. Go to 'Magistrix Lambriesse', 'Debbi Moore', or 'Arcanist Ivrenne', all inside dalaran, with 40 emblems of heroism, purchase "The Egg of Mortal Essence"'
2. Talent down into "Siphon Life" in the Affliction Tree
3. Use Corruption on a mob, and keep it rolling, or reapplying it. Observe if a haste proc occurs.

**Comment by nodddle** [comment]
see here: https://github.com/Zephancode/wotlk-warlock/issues/1

according to this, siphon life is unable to proc egg.
