### ISSUE TITLE
[TEST-REQUEST] Rolling Corruption

### ISSUE THREAD

**Issue by Hathos** [Zephancode/wotlk-warlock#6]
## 1. Describe the mechanic
[Corruption](https://wotlkdb.com/?spell=47813) has two ways to be refreshed in Wrath of the Lich King (WotLK). First, is a hard refresh, which is recasting it before it falls off. Second, is a soft refresh, which is when it is refreshed by the talent [Everlasting Affliction](https://wotlkdb.com/?spell=47205). This talent allows Drain Life, Drain Soul, Shadow Bolt, and Haunt to refresh the duration of Corruption.

In WotLK, different stats contributing to Corruption were snapshotted based on how the Corruption itself was refreshed.

The below stats snapshot when Corruption is cast and only refresh on a hard refresh. This allows the stats to "roll" for the entire duration that Corruption is kept up without falling:

- Critical strike chance
- Percentage damage modifiers
- Various boss mechanics

The below stats snapshot when Corruption is cast, but also refresh on a soft refresh. This means that at most they are snapshotted for 18 seconds, since they recalculate/update however Corruption is refreshed:

- Spellpower
- Haste
- Various boss mechanics

The question is if it will still behave this way in WotLK Classic. The developers at the time acknowledged the final state of the rolling mechanic as a clever use of game mechanics. As for the various boss mechanics, you can find old testing results for each [here](https://web.archive.org/web/20100531074742/http://shadowpriest.com/viewtopic.php?f=61&t=23642) and [here](https://www.mmo-champion.com/threads/690864-Affliction-Learning-to-corrupt). For the scope of this issue, it will be critical strike, percentage damage, spellpower, and haste.

### 1.1 To Test
Steps to test the behavior:
1. Determine base damage for corruption
2. Find a Rogue to give you Tricks of the Trade
3. Apply a corruption while you have Tricks of the Trade
4. Check to see if the % damage bonus from Tricks of the Trade still persists after Corruption is refreshed via Everlasting Affliction.

**Comment by nodddle** [comment]
I tested this with a nice level 75 rogue I found in /who. when I put up corruption without tricks it ticks for 415. he put up tricks on me, I put up corruption, it ticked for 477, then I refreshed it with drain life and it continued to tick for 477, then I refreshed it again and again and it always ticked for 477 despite not having the tricks buff when refreshing it. 415*1.15=477.

**Comment by Zephancode** [comment]
# Crit Rolling
I tested the following scenario and confirmed that crit rating does indeed role over after the initial application.

## Test Case
1. Talented into Malediction 9% Crit
2. Applied ISB 5% Crit Rating
3. Apply Corruption
4. Swap out crit weapons (15.7% -> 12.31% on char pane)
5. Let ISB run out and keep corruption up via Drain Soul

Crit with gear and ISB = 29.7%
Without = 21.31 %

## Results
1804 Total Ticks, 558 critical ticks = 30.93 % crits

## Evidence
https://docs.google.com/spreadsheets/d/1_hVzcy2dirKcdsSW1Cu_oumSNeSa2OcuFCyKXB7Ai8o/edit#gid=0
Build: 3.4.0.44463

**Comment by nodddle** [comment]
https://youtu.be/CEa4WsCkBRo
here's the footage of my tricks testing.
