### ISSUE TITLE
MECHANIC: Does Improved Curse of Agony still only affect base damage.

### ISSUE THREAD

**Issue by Zephancode** [Zephancode/wotlk-warlock#8]
In Classic and The Burning Crusade, the talent Improved Curse of Agony only affected the base damage (before spell power damage) of the spell.

It should be tested if this is still the case for WoTLK version of the talent. The same goes for Improved Corruption.

**Comment by Shukrat** [comment]
Appears to affect spellpower as well. Did Curse of Agony without talent, did 2748 damage.  After talent (2 points), did 3023 damage. That's 10% more than 2748. If it was just base the overall increase would have been substantially less.

Same story for corruption 
![image](https://user-images.githubusercontent.com/6796294/175290136-6c2a2fe4-05c4-48ea-95a9-2349cf152e3f.png)

**Comment by Zephancode** [comment]
Great stuff, for completionist's sake: how much spell power, did you have during testing?

**Comment by Shukrat** [comment]
1160 or so. Don't remember the specific buffs I had, but I tried to keep it all minimal to just local buffs, no food or flask etc.
